version: "3"

services:
  reverse_proxy:
    build: .
    container_name: "reverse_proxy"
    restart: always
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
      - ./logs/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy-network
      - default

networks:
  reverse-proxy-network:
    external: true