version: "3"

services:
  reverse_proxy:
    build: .
    container_name: "ReverseProxy"
    restart: always
    network_mode: "host"
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
      - ./logs/:/var/log/nginx/
