version: "3"

services:
  reverse_proxy:
    build: .
    container_name: "ReverseProxy"
    restart: always
    net: host
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
      - ./logs/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"