version: "3"

services:
  router:
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
      - ./logs/:/var/log/nginx/
      
networks:
  docker-access-route-network:
    external: true